import * as cardsImages from './';

export const cards = {
    twoOfClubs: cardsImages['2C.png'],
    threeOfClubs: cardsImages['3C.png'],
    fourOfClubs: cardsImages['4C.png'],
    fiveOfClubs: cardsImages['5C.png'],
    sixOfClubs: cardsImages['6C.png'],
    sevenOfClubs: cardsImages['7C.png'],
    eightOfClubs: cardsImages['8C.png'],
    nineOfClubs: cardsImages['9C.png'],
    tenOfClubs: cardsImages['10C.png'],
    jackOfClubs: cardsImages['JC.png'],
    queenOfClubs: cardsImages['QC.png'],
    kingOfClubs: cardsImages['KC.png'],
    aceOfClubs: cardsImages['AC.png'],

    twoOfDiamonds: cardsImages['2D.png'],
    threeOfDiamonds: cardsImages['3D.png'],
    fourOfDiamonds: cardsImages['4D.png'],
    fiveOfDiamonds: cardsImages['5D.png'],
    sixOfDiamonds: cardsImages['6D.png'],
    sevenOfDiamonds: cardsImages['7D.png'],
    eightOfDiamonds: cardsImages['8D.png'],
    nineOfDiamonds: cardsImages['9D.png'],
    tenOfDiamonds: cardsImages['10D.png'],
    jackOfDiamonds: cardsImages['JD.png'],
    queenOfDiamonds: cardsImages['QD.png'],
    kingOfDiamonds: cardsImages['KD.png'],
    aceOfDiamonds: cardsImages['AD.png'],

    twoOfHearts: cardsImages['2H.png'],
    threeOfHearts: cardsImages['3H.png'],
    fourOfHearts: cardsImages['4H.png'],
    fiveOfHearts: cardsImages['5H.png'],
    sixOfHearts: cardsImages['6H.png'],
    sevenOfHearts: cardsImages['7H.png'],
    eightOfHearts: cardsImages['8H.png'],
    nineOfHearts: cardsImages['9H.png'],
    tenOfHearts: cardsImages['10H.png'],
    jackOfHearts: cardsImages['JH.png'],
    queenOfHearts: cardsImages['QH.png'],
    kingOfHearts: cardsImages['KH.png'],
    aceOfHearts: cardsImages['AH.png'],

    twoOfSpades: cardsImages['2S.png'],
    threeOfSpades: cardsImages['3S.png'],
    fourOfSpades: cardsImages['4S.png'],
    fiveOfSpades: cardsImages['5S.png'],
    sixOfSpades: cardsImages['6S.png'],
    sevenOfSpades: cardsImages['7S.png'],
    eightOfSpades: cardsImages['8S.png'],
    nineOfSpades: cardsImages['9S.png'],
    tenOfSpades: cardsImages['10S.png'],
    jackOfSpades: cardsImages['JS.png'],
    queenOfSpades: cardsImages['QS.png'],
    kingOfSpades: cardsImages['KS.png'],
    aceOfSpades: cardsImages['AS.png']
};
